# Generated by Django 3.2.9 on 2022-01-29 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productLink', models.TextField(blank=True, max_length=200)),
                ('sku', models.TextField(blank=True, max_length=200)),
                ('productName', models.TextField(blank=True, max_length=200)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('stock', models.IntegerField(blank=True)),
                ('sales', models.IntegerField(blank=True)),
                ('price', models.TextField(blank=True, max_length=200)),
                ('discount', models.TextField(blank=True, max_length=200)),
                ('beforeDiscount', models.TextField(blank=True, max_length=200)),
                ('brand', models.TextField(blank=True, max_length=200)),
                ('image', models.URLField(blank=True)),
                ('sellerName', models.TextField(blank=True, max_length=200)),
                ('sellerRating', models.TextField(blank=True, max_length=200)),
                ('chatRespomse', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True)),
                ('product', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
