# Generated by Django 3.2.9 on 2022-01-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='staticavator.png', null=True, upload_to=''),
        ),
    ]
